config/routes.rb
Shipping::Application.routes.draw do
  get "search/search_ship"

  resources :shipping_line_offices

  resources :trips

  resources :ports

  resources :ships

  resources :shipping_lines

  root :to => 'search#search_ship'
    
  match 'search_ship' => 'search#search_ship', :as => :search_ship

end

app/models/port.rb
class Port < ActiveRecord::Base
  attr_accessible :city, :country, :ocean, :port_name, :state

  validates :port_name, :uniqueness => true

  has_many :shipping_line_offices
  has_many :trips
end

app/controllers/ports_controller.rb
class PortsController < ApplicationController
  # GET /ports
  # GET /ports.json
  def index
    @ports = Port.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @ports }
    end
  end

  # GET /ports/1
  # GET /ports/1.json
  def show
    @port = Port.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @port }
    end
  end

  # GET /ports/new
  # GET /ports/new.json
  def new
    @port = Port.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @port }
    end
  end

  # GET /ports/1/edit
  def edit
    @port = Port.find(params[:id])
  end

  # POST /ports
  # POST /ports.json
  def create
    @port = Port.new(params[:port])

    respond_to do |format|
      if @port.save
        format.html { redirect_to @port, :notice => 'Port was successfully created.' }
        format.json { render :json => @port, :status => :created, :location => @port }
      else
        format.html { render :action => "new" }
        format.json { render :json => @port.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ports/1
  # PUT /ports/1.json
  def update
    @port = Port.find(params[:id])

    respond_to do |format|
      if @port.update_attributes(params[:port])
        format.html { redirect_to @port, :notice => 'Port was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @port.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ports/1
  # DELETE /ports/1.json
  def destroy
    @port = Port.find(params[:id])
    @port.destroy

    respond_to do |format|
      format.html { redirect_to ports_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/ports_helper.rb
module PortsHelper
end

app/views/ports/_form.html.erb
<%= form_for(@port) do |f| %>
  <% if @port.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@port.errors.count, "error") %> prohibited this port from being saved:</h2>

      <ul>
      <% @port.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :port_name %><br />
    <%= f.text_field :port_name %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :ocean %><br />
    <%= f.text_field :ocean %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ports/edit.html.erb
<h1>Editing port</h1>

<%= render 'form' %>

<%= link_to 'Show', @port %> |
<%= link_to 'Back', ports_path %>

app/views/ports/index.html.erb
<h1>Listing ports</h1>

<table>
  <tr>
    <th>Port name</th>
    <th>City</th>
    <th>State</th>
    <th>Country</th>
    <th>Ocean</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ports.each do |port| %>
  <tr>
    <td><%= port.port_name %></td>
    <td><%= port.city %></td>
    <td><%= port.state %></td>
    <td><%= port.country %></td>
    <td><%= port.ocean %></td>
    <td><%= link_to 'Show', port %></td>
    <td><%= link_to 'Edit', edit_port_path(port) %></td>
    <td><%= link_to 'Destroy', port, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Port', new_port_path %>

app/views/ports/new.html.erb
<h1>New port</h1>

<%= render 'form' %>

<%= link_to 'Back', ports_path %>

app/views/ports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Port name:</b>
  <%= @port.port_name %>
</p>

<p>
  <b>City:</b>
  <%= @port.city %>
</p>

<p>
  <b>State:</b>
  <%= @port.state %>
</p>

<p>
  <b>Country:</b>
  <%= @port.country %>
</p>

<p>
  <b>Ocean:</b>
  <%= @port.ocean %>
</p>


<%= link_to 'Edit', edit_port_path(@port) %> |
<%= link_to 'Back', ports_path %>