config/routes.rb
Shipping::Application.routes.draw do
  get "search/search_ship"

  resources :shipping_line_offices

  resources :trips

  resources :ports

  resources :ships

  resources :shipping_lines

  root :to => 'search#search_ship'
    
  match 'search_ship' => 'search#search_ship', :as => :search_ship

end

app/models/shipping_line.rb
class ShippingLine < ActiveRecord::Base
  attr_accessible :address, :city, :company_name, :contact_email, :contact_person, :contact_phone, :country, :description, :state

  validates :contact_email, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create }
  validates :contact_phone, :numericality => true	

  has_many :ships
  has_many :shipping_line_offices
end

app/controllers/shipping_lines_controller.rb
class ShippingLinesController < ApplicationController
  # GET /shipping_lines
  # GET /shipping_lines.json
  def index
    @shipping_lines = ShippingLine.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @shipping_lines }
    end
  end

  # GET /shipping_lines/1
  # GET /shipping_lines/1.json
  def show
    @shipping_line = ShippingLine.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @shipping_line }
    end
  end

  # GET /shipping_lines/new
  # GET /shipping_lines/new.json
  def new
    @shipping_line = ShippingLine.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @shipping_line }
    end
  end

  # GET /shipping_lines/1/edit
  def edit
    @shipping_line = ShippingLine.find(params[:id])
  end

  # POST /shipping_lines
  # POST /shipping_lines.json
  def create
    @shipping_line = ShippingLine.new(params[:shipping_line])

    respond_to do |format|
      if @shipping_line.save
        format.html { redirect_to @shipping_line, :notice => 'Shipping line was successfully created.' }
        format.json { render :json => @shipping_line, :status => :created, :location => @shipping_line }
      else
        format.html { render :action => "new" }
        format.json { render :json => @shipping_line.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /shipping_lines/1
  # PUT /shipping_lines/1.json
  def update
    @shipping_line = ShippingLine.find(params[:id])

    respond_to do |format|
      if @shipping_line.update_attributes(params[:shipping_line])
        format.html { redirect_to @shipping_line, :notice => 'Shipping line was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @shipping_line.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /shipping_lines/1
  # DELETE /shipping_lines/1.json
  def destroy
    @shipping_line = ShippingLine.find(params[:id])
    @shipping_line.destroy

    respond_to do |format|
      format.html { redirect_to shipping_lines_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/shipping_lines_helper.rb
module ShippingLinesHelper
end

app/views/shipping_lines/_form.html.erb
<%= form_for(@shipping_line) do |f| %>
  <% if @shipping_line.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shipping_line.errors.count, "error") %> prohibited this shipping_line from being saved:</h2>

      <ul>
      <% @shipping_line.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :contact_person %><br />
    <%= f.text_field :contact_person %>
  </div>
  <div class="field">
    <%= f.label :contact_email %><br />
    <%= f.email_field :contact_email %>
  </div>
  <div class="field">
    <%= f.label :contact_phone %><br />
    <%= f.phone_field :contact_phone %>
  </div>
  <div class="field">
    <%= f.label :company_name %><br />
    <%= f.text_field :company_name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shipping_lines/edit.html.erb
<h1>Editing shipping_line</h1>

<%= render 'form' %>

<%= link_to 'Show', @shipping_line %> |
<%= link_to 'Back', shipping_lines_path %>

app/views/shipping_lines/index.html.erb
<h1>Listing shipping_lines</h1>

<table>
  <tr>
    <th>Address</th>
    <th>City</th>
    <th>State</th>
    <th>Country</th>
    <th>Contact person</th>
    <th>Contact email</th>
    <th>Contact phone</th>
    <th>Company name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shipping_lines.each do |shipping_line| %>
  <tr>
    <td><%= shipping_line.address %></td>
    <td><%= shipping_line.city %></td>
    <td><%= shipping_line.state %></td>
    <td><%= shipping_line.country %></td>
    <td><%= shipping_line.contact_person %></td>
    <td><%= shipping_line.contact_email %></td>
    <td><%= shipping_line.contact_phone %></td>
    <td><%= shipping_line.company_name %></td>
    <td><%= shipping_line.description %></td>
    <td><%= link_to 'Show', shipping_line %></td>
    <td><%= link_to 'Edit', edit_shipping_line_path(shipping_line) %></td>
    <td><%= link_to 'Destroy', shipping_line, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Shipping line', new_shipping_line_path %>

app/views/shipping_lines/new.html.erb
<h1>New shipping_line</h1>

<%= render 'form' %>

<%= link_to 'Back', shipping_lines_path %>

app/views/shipping_lines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Address:</b>
  <%= @shipping_line.address %>
</p>

<p>
  <b>City:</b>
  <%= @shipping_line.city %>
</p>

<p>
  <b>State:</b>
  <%= @shipping_line.state %>
</p>

<p>
  <b>Country:</b>
  <%= @shipping_line.country %>
</p>

<p>
  <b>Contact person:</b>
  <%= @shipping_line.contact_person %>
</p>

<p>
  <b>Contact email:</b>
  <%= @shipping_line.contact_email %>
</p>

<p>
  <b>Contact phone:</b>
  <%= @shipping_line.contact_phone %>
</p>

<p>
  <b>Company name:</b>
  <%= @shipping_line.company_name %>
</p>

<p>
  <b>Description:</b>
  <%= @shipping_line.description %>
</p>


<%= link_to 'Edit', edit_shipping_line_path(@shipping_line) %> |
<%= link_to 'Back', shipping_lines_path %>