config/routes.rb
Shipping::Application.routes.draw do
  get "search/search_ship"

  resources :shipping_line_offices

  resources :trips

  resources :ports

  resources :ships

  resources :shipping_lines

  root :to => 'search#search_ship'
    
  match 'search_ship' => 'search#search_ship', :as => :search_ship

end

app/models/ship.rb
class Ship < ActiveRecord::Base
  attr_accessible :cbf_bale, :dw, :gear, :name, :ship_type, :shipping_line_id

  validates :cbf_bale, :numericality => true
  validates :dw, :numericality => true

  belongs_to :shipping_line
  has_many :trips
end

app/controllers/ships_controller.rb
class ShipsController < ApplicationController
  # GET /ships
  # GET /ships.json
  def index
    @ships = Ship.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @ships }
    end
  end

  # GET /ships/1
  # GET /ships/1.json
  def show
    @ship = Ship.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @ship }
    end
  end

  # GET /ships/new
  # GET /ships/new.json
  def new
    @ship = Ship.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @ship }
    end
  end

  # GET /ships/1/edit
  def edit
    @ship = Ship.find(params[:id])
  end

  # POST /ships
  # POST /ships.json
  def create
    @ship = Ship.new(params[:ship])

    respond_to do |format|
      if @ship.save
        format.html { redirect_to @ship, :notice => 'Ship was successfully created.' }
        format.json { render :json => @ship, :status => :created, :location => @ship }
      else
        format.html { render :action => "new" }
        format.json { render :json => @ship.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ships/1
  # PUT /ships/1.json
  def update
    @ship = Ship.find(params[:id])

    respond_to do |format|
      if @ship.update_attributes(params[:ship])
        format.html { redirect_to @ship, :notice => 'Ship was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @ship.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ships/1
  # DELETE /ships/1.json
  def destroy
    @ship = Ship.find(params[:id])
    @ship.destroy

    respond_to do |format|
      format.html { redirect_to ships_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/ships_helper.rb
module ShipsHelper
end

app/views/ships/_form.html.erb
<%= form_for(@ship) do |f| %>
  <% if @ship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ship.errors.count, "error") %> prohibited this ship from being saved:</h2>

      <ul>
      <% @ship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ship_type %><br />
    <%= f.text_field :ship_type %>
  </div>
  <div class="field">
    <%= f.label :dw %><br />
    <%= f.number_field :dw %>
  </div>
  <div class="field">
    <%= f.label :cbf_bale %><br />
    <%= f.number_field :cbf_bale %>
  </div>
  <div class="field">
    <%= f.label :gear %><br />
    <%= f.text_field :gear %>
  </div>
  <div class="field">
    <%= f.label :shipping_line_id %><br />
    <%= collection_select (:ship, :shipping_line_id, ShippingLine.all, :id, :company_name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ships/edit.html.erb
<h1>Editing ship</h1>

<%= render 'form' %>

<%= link_to 'Show', @ship %> |
<%= link_to 'Back', ships_path %>

app/views/ships/index.html.erb
<h1>Listing ships</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Ship Type</th>
    <th>Dw</th>
    <th>Cbf bale</th>
    <th>Gear</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ships.each do |ship| %>
  <tr>
    <td><%= ship.name %></td>
    <td><%= ship.ship_type %></td>
    <td><%= ship.dw %></td>
    <td><%= ship.cbf_bale %></td>
    <td><%= ship.gear %></td>
    <td><%= link_to 'Show', ship %></td>
    <td><%= link_to 'Edit', edit_ship_path(ship) %></td>
    <td><%= link_to 'Destroy', ship, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ship', new_ship_path %>

app/views/ships/new.html.erb
<h1>New ship</h1>

<%= render 'form' %>

<%= link_to 'Back', ships_path %>

app/views/ships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @ship.name %>
</p>

<p>
  <b> Ship Type:</b>
  <%= @ship.ship_type %>
</p>

<p>
  <b>Dw:</b>
  <%= @ship.dw %>
</p>

<p>
  <b>Cbf bale:</b>
  <%= @ship.cbf_bale %>
</p>

<p>
  <b>Gear:</b>
  <%= @ship.gear %>
</p>


<%= link_to 'Edit', edit_ship_path(@ship) %> |
<%= link_to 'Back', ships_path %>