config/routes.rb
Shipping::Application.routes.draw do
  get "search/search_ship"

  resources :shipping_line_offices

  resources :trips

  resources :ports

  resources :ships

  resources :shipping_lines

  root :to => 'search#search_ship'
    
  match 'search_ship' => 'search#search_ship', :as => :search_ship

end

app/models/shipping_line_office.rb
class ShippingLineOffice < ActiveRecord::Base
  attr_accessible :area_address, :shipping_line_id, :port_id

  belongs_to :shipping_line
  belongs_to :port
end

app/controllers/shipping_line_offices_controller.rb
class ShippingLineOfficesController < ApplicationController
  # GET /shipping_line_offices
  # GET /shipping_line_offices.json
  def index
    @shipping_line_offices = ShippingLineOffice.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @shipping_line_offices }
    end
  end

  # GET /shipping_line_offices/1
  # GET /shipping_line_offices/1.json
  def show
    @shipping_line_office = ShippingLineOffice.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @shipping_line_office }
    end
  end

  # GET /shipping_line_offices/new
  # GET /shipping_line_offices/new.json
  def new
    @shipping_line_office = ShippingLineOffice.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @shipping_line_office }
    end
  end

  # GET /shipping_line_offices/1/edit
  def edit
    @shipping_line_office = ShippingLineOffice.find(params[:id])
  end

  # POST /shipping_line_offices
  # POST /shipping_line_offices.json
  def create
    @shipping_line_office = ShippingLineOffice.new(params[:shipping_line_office])

    respond_to do |format|
      if @shipping_line_office.save
        format.html { redirect_to @shipping_line_office, :notice => 'Shipping line office was successfully created.' }
        format.json { render :json => @shipping_line_office, :status => :created, :location => @shipping_line_office }
      else
        format.html { render :action => "new" }
        format.json { render :json => @shipping_line_office.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /shipping_line_offices/1
  # PUT /shipping_line_offices/1.json
  def update
    @shipping_line_office = ShippingLineOffice.find(params[:id])

    respond_to do |format|
      if @shipping_line_office.update_attributes(params[:shipping_line_office])
        format.html { redirect_to @shipping_line_office, :notice => 'Shipping line office was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @shipping_line_office.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /shipping_line_offices/1
  # DELETE /shipping_line_offices/1.json
  def destroy
    @shipping_line_office = ShippingLineOffice.find(params[:id])
    @shipping_line_office.destroy

    respond_to do |format|
      format.html { redirect_to shipping_line_offices_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/shipping_line_offices_helper.rb
module ShippingLineOfficesHelper
end

app/views/shipping_line_offices/_form.html.erb
<%= form_for(@shipping_line_office) do |f| %>
  <% if @shipping_line_office.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shipping_line_office.errors.count, "error") %> prohibited this shipping_line_office from being saved:</h2>

      <ul>
      <% @shipping_line_office.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :area_address %><br />
    <%= f.text_field :area_address %>
  </div>
  <div class="field">
    <%= f.label :shipping_line_id %><br />
    <%= collection_select (:shipping_line_office, :shipping_line_id, ShippingLine.all, :id, :company_name) %>
  </div>
  <div class="field">
    <%= f.label :port_id %><br />
    <%= collection_select (:shipping_line_office, :port_id, Port.all, :id, :port_name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shipping_line_offices/edit.html.erb
<h1>Editing shipping_line_office</h1>

<%= render 'form' %>

<%= link_to 'Show', @shipping_line_office %> |
<%= link_to 'Back', shipping_line_offices_path %>

app/views/shipping_line_offices/index.html.erb
<h1>Listing shipping_line_offices</h1>

<table>
  <tr>
    <th>Area address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shipping_line_offices.each do |shipping_line_office| %>
  <tr>
    <td><%= shipping_line_office.area_address %></td>
    <td><%= link_to 'Show', shipping_line_office %></td>
    <td><%= link_to 'Edit', edit_shipping_line_office_path(shipping_line_office) %></td>
    <td><%= link_to 'Destroy', shipping_line_office, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Shipping line office', new_shipping_line_office_path %>

app/views/shipping_line_offices/new.html.erb
<h1>New shipping_line_office</h1>

<%= render 'form' %>

<%= link_to 'Back', shipping_line_offices_path %>

app/views/shipping_line_offices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Area address:</b>
  <%= @shipping_line_office.area_address %>
</p>


<%= link_to 'Edit', edit_shipping_line_office_path(@shipping_line_office) %> |
<%= link_to 'Back', shipping_line_offices_path %>